---
abstract: 'Perl extension for managing ISO thesaurus'
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.120921'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Biblio-Thesaurus
no_index:
  directory:
    - t
    - inc
requires:
  CGI: 0
  Storable: 1.0006
  Test::More: 0
  XML::TMX: 0.12
version: 0.43
